### PR TITLE
Added a name parameter for the `except_math_error` function to make math errors prettier.

### PR DESCRIPTION
**Pull request by sayaks**
This way, the bot won't say things like:
`Error: Can't run <lambda> function on value "user defined function"`
and instead it'll say:
`Error: Can't run gamma function on value "user defined function"`

In case i missed one use of this function, it has a default argument of "name not provided".

### CODE REVIEW

**Comment by LaVieEstDure** [comment]
Nevermind, I spoke too late

**Comment by sayaks** [comment]
Heh, i noticed that too.

**Comment by DXsmiley** [comment]
Seeing as you're updating all the `EvaluationError`s, you should checkout the [definition of it](https://github.com/DXsmiley/mathbot/blob/master/mathbot/calculator/errors.py) in order to make the code neater.

**Comment by sayaks** [comment]
I'm not actually changing the evaluation errors, all I'm doing is breaking up one of the lines that got too long. I can check out the definition of it later tho, not sure how relevant it is to this pr.

**Comment by thetrentus** [comment]
Once DX has reviewed this I think it can be merged into the main repo. Also collaborators do have the technical ability to merge their own reviews but code review by peers never hurts

**Comment by bmintz** [comment]
I suppose if we stopped using lambda functions this wouldn't be an issue in the first place, right? Or am I totally off here?

**Pull request merged**
